name: DataBackup
main: net.okocraft.databackup.DataBackup
version: ${project.version}
api-version: "1.15"
author: Siroshun09
softdepend:
  - "UserAPI"
  - "Vault"
  - "mcMMO"
commands:
  databackup:
    aliases: [db]
